apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: weather-api-server
  name: weather-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: weather-api-server
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: weather-api-server
    spec:
      containers:
        - env:
            - name: REDIS_URL
              value: redis://redis-cache:6379
          image: weather-go-app:dev
          name: weather-api-server
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
