apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: weather-api-server
  name: weather-api-server
spec:
  ports:
    - name: "12345"
      port: 12345
      targetPort: 8080
  selector:
    io.kompose.service: weather-api-server
